// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_balance is a generated GoMock package.
package mock_balance

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	balance "github.com/klyakssa/go-diplom.git/internal/domain/balance"
	decimal "github.com/shopspring/decimal"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetBalanceWithdrawn mocks base method.
func (m *MockRepository) GetBalanceWithdrawn(ctx context.Context, userID string) (decimal.Decimal, decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceWithdrawn", ctx, userID)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(decimal.Decimal)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBalanceWithdrawn indicates an expected call of GetBalanceWithdrawn.
func (mr *MockRepositoryMockRecorder) GetBalanceWithdrawn(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceWithdrawn", reflect.TypeOf((*MockRepository)(nil).GetBalanceWithdrawn), ctx, userID)
}

// GetWithdrawls mocks base method.
func (m *MockRepository) GetWithdrawls(ctx context.Context, userID string) ([]balance.WithdrawHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawls", ctx, userID)
	ret0, _ := ret[0].([]balance.WithdrawHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawls indicates an expected call of GetWithdrawls.
func (mr *MockRepositoryMockRecorder) GetWithdrawls(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawls", reflect.TypeOf((*MockRepository)(nil).GetWithdrawls), ctx, userID)
}

// WithdrawBalance mocks base method.
func (m *MockRepository) WithdrawBalance(ctx context.Context, userID, orderNumber string, amount decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawBalance", ctx, userID, orderNumber, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithdrawBalance indicates an expected call of WithdrawBalance.
func (mr *MockRepositoryMockRecorder) WithdrawBalance(ctx, userID, orderNumber, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawBalance", reflect.TypeOf((*MockRepository)(nil).WithdrawBalance), ctx, userID, orderNumber, amount)
}
