// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_balance is a generated GoMock package.
package mock_balance

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	balance "github.com/klyakssa/go-diplom.git/internal/domain/balance"
	decimal "github.com/shopspring/decimal"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetBalanceWithdrawn mocks base method.
func (m *MockService) GetBalanceWithdrawn(ctx context.Context, userID string) (decimal.Decimal, decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceWithdrawn", ctx, userID)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(decimal.Decimal)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBalanceWithdrawn indicates an expected call of GetBalanceWithdrawn.
func (mr *MockServiceMockRecorder) GetBalanceWithdrawn(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceWithdrawn", reflect.TypeOf((*MockService)(nil).GetBalanceWithdrawn), ctx, userID)
}

// GetWithdrawls mocks base method.
func (m *MockService) GetWithdrawls(ctx context.Context, userID string) ([]balance.WithdrawHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawls", ctx, userID)
	ret0, _ := ret[0].([]balance.WithdrawHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawls indicates an expected call of GetWithdrawls.
func (mr *MockServiceMockRecorder) GetWithdrawls(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawls", reflect.TypeOf((*MockService)(nil).GetWithdrawls), ctx, userID)
}

// WithdrawBalance mocks base method.
func (m *MockService) WithdrawBalance(ctx context.Context, userID, orderNumber string, amount decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawBalance", ctx, userID, orderNumber, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithdrawBalance indicates an expected call of WithdrawBalance.
func (mr *MockServiceMockRecorder) WithdrawBalance(ctx, userID, orderNumber, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawBalance", reflect.TypeOf((*MockService)(nil).WithdrawBalance), ctx, userID, orderNumber, amount)
}
